### ISSUE TITLE
rescale the training image, view do not match

### ISSUE THREAD

**Issue by mozpp** [XingangPan/SCNN#22]
Hi, I want to rescale the input image to 640*360. I modified lane.lua, and find out 
`/home/user/torch/install/share/lua/5.1/nn/View.lua:47: input view (3x128x80) and desired view (128x1x100) do not match
`
how to modify the model?

**Comment by mozpp** [comment]
I see another issue [https://github.com/XingangPan/SCNN/issues/7](url), how to modify the pretrained VGG model?(the vgg.t7 file?)

**Comment by XingangPan** [comment]
@mozpp  For example, in order to change the nn.View(4500) to nn.View(4600), you can do as follows:
require 'nn'
require 'cudnn'
model = torch.load('vgg/vgg.t7')
classifier = model:get(44):get(2)
classifier:remove(3)
classifier:insert(nn.View(4600), 3)
print(model)

In a word, the 'get', 'remove', and 'insert' function of the 'Containers' class will do. Check https://github.com/torch/nn/blob/master/doc/containers.md#nn.Containers for more details.

**Comment by mozpp** [comment]
@XingangPan thanks!
